#
# sdl/makefile.cfg for SRB2/SDL
#

#
#SDL...., *looks at Alam*, THIS IS A MESS!
#

ifdef UNIXLIKE
include sdl/makeNIX.cfg
endif

ifdef DC
include sdl/SRB2DC/makefile.cfg
endif #ifdef DC

ifdef PSP
include sdl/SRB2PSP/makefile.cfg
endif #ifdef PSP

ifdef XBOX
include sdl/SRB2XBOX/makefile.cfg
endif #ifdef XBOX

ifdef WINCE
include sdl/SRB2CE/makefile.cfg
endif #ifef WINCE

ifdef CYGWIN32
include sdl/makeCYG.cfg
endif #ifdef CYGWIN32

ifdef SDLIO
	OPTS += -DSDLIO
endif

ifndef NO_SDL_CONFIG
	SDL_CONFIG ?= sdl-config
	SDL_CFLAGS := $(shell $(SDL_CONFIG) --cflags)
	SDL_LDFLAGS := $(shell $(SDL_CONFIG) --libs)
endif

	#use the x86 asm code
ifndef CYGWIN32
ifndef NOASM
	USEASM=1
endif
endif

	OBJS += $(OBJDIR)/i_video.o $(OBJDIR)/dosstr.o $(OBJDIR)/endtxt.o $(OBJDIR)/hwsym_sdl.o

	OPTS += -DDIRECTFULLSCREEN -DSDL

ifndef NOHW
	OBJS += $(OBJDIR)/r_opengl.o $(OBJDIR)/ogl_sdl.o
endif

ifndef NOHS
ifdef OPENAL
	OBJS += $(OBJDIR)/s_openal.o
	OPTS += -DSTATIC3DS
	STATICHS = 1
else
ifdef FMOD
	OBJS += $(OBJDIR)/s_fmod.o
	OPTS += -DSTATIC3DS
	STATICHS = 1
else
ifdef MINGW
ifdef DS3D
	OBJS += $(OBJDIR)/s_ds3d.o
	OPTS += -DSTATIC3DS
	STATICHS = 1
endif
endif
endif
endif
endif

ifndef NOFILTERS
	OBJS += $(OBJDIR)/filters.o $(OBJDIR)/hq2x.o $(OBJDIR)/lq2x.o
	OPTS += -DHAVE_FILTER
endif

ifndef NOMIXER
	OPTS += -DHAVE_MIXER
	SDL_LDFLAGS += -lSDL_mixer
endif

ifdef SDL_IMAGE
	OPTS += -DHAVE_IMAGE
	SDL_LDFLAGS += -lSDL_image
endif

ifdef SDL_NET
	OPTS += -DHAVE_SDLNET
	SDL_LDFLAGS += -lSDL_net
endif

ifdef MINGW
ifndef NOHW
	LIBS := -lopengl32 -lglu32 $(LIBS)
endif

else

ifndef NOHW
ifdef DC
	LIBS := -lgl $(LIBS)
else
ifdef PSP
	LIBS := -lGLU -lGL $(LIBS)
else
	LIBS := -lGL -lGLU $(LIBS)
endif
endif
endif
endif

ifdef SDLMAIN
	OPTS += -DSDLMAIN
	LIBS := -lSDLmain $(LIBS)
ifdef MINGW
	LIBS := -lmingw32 $(LIBS) -mwindows
endif
endif

ifndef NOHW
ifdef OPENAL
ifdef MINGW
	LIBS := -lopenal32 $(LIBS)
else
	LIBS := -lopenal $(LIBS)
endif
else
ifdef FMOD
	LIBS := -lfmod $(LIBS)
else
ifdef MINGW
ifdef DS3D
	LIBS := -ldsound -luuid $(LIBS)
endif
endif
endif
endif
endif

CFLAGS := $(CFLAGS) $(SDL_CFLAGS)
LIBS := $(SDL_LDFLAGS) $(LIBS)
ifdef MINGW
ifndef SDLMAIN
CFLAGS := $(CFLAGS) -Umain
endif
endif

